### ISSUE TITLE
Where is the IntelliJ plugin?

### ISSUE THREAD

**Issue by g123k** [andrasferenczi/idea_widget_preview#1]
Hello,

I can't find the plugin in IntelliJ's marketplace.
Do you have a link to it?

Thanks

**Comment by andrasferenczi** [comment]
Hi,

It will be available shortly. (Hopefully in a week or so.)

Final touches take longer than expected.

I'll keep you updated about the release.

**Comment by andrasferenczi** [comment]
Just wanted to let you know that the [plugin](https://plugins.jetbrains.com/plugin/20292-widget-preview-for-flutter) is available now.

I will close this issue once I update the relevant readme files.
