### ISSUE TITLE
Plugin creates a dart file in every opened Flutter project

### ISSUE THREAD

**Issue by westito** [andrasferenczi/idea_widget_preview#4]
The plugin also creates a "widget.preview.dart" file in Flutter projects that doesn't use this package

<img width="273" alt="Képernyőfotó 2022-12-07 - 17 48 35" src="https://user-images.githubusercontent.com/536799/206240027-64f2fad9-43d9-4e0d-a0fc-3c28fff17428.png">

**Comment by andrasferenczi** [comment]
Fixed in `v2022.1.5`. Update has been released, will be available in a couple days probably.
